[package]
name = "source-kv"
description = "A Serde serialization and deserialization library for Valve's Key-Value format."
readme = "README.md"
keywords = ["source-engine", "sdk", "gamedev"]
categories = ["game-development"]
repository = "https://github.com/LaVashikk/SourceRS/tree/main/crates/source-kv"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
indexmap = { workspace = true, features = ["serde"] }

[dev-dependencies]
serde_derive.workspace = true
