[package]
name = "source-fs"
description = "A virtual filesystem implementation for Source Engine games, handling gameinfo.txt search paths, VPK archives, and cross-platform file resolution."
readme = "README.md"
keywords = ["source-engine", "filesystem", "vpk", "gamedev"]
categories = ["game-development", "filesystem"]
repository = "https://github.com/LaVashikk/SourceRS/tree/main/crates/source-fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
source-vpk.workspace = true
thiserror.workspace = true
steamlocate = { workspace = true, optional = true }

[dev-dependencies]
crc32fast.workspace = true
tempfile.workspace = true

[features]
default = []
steam = ["dep:steamlocate"]
