[package]
name = "source-vmf"
description = "A parser for Valve Map Format (VMF) files"
repository = "https://github.com/LaVashikk/SourceRS/tree/main/crates/source-vmf"
documentation = "https://docs.rs/source-vmf"
readme = "README.md"
keywords = ["vmf", "valve", "map", "parser", "source"]
categories = ["parser-implementations", "game-development"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
pest.workspace = true
pest_derive.workspace = true
indexmap.workspace = true
derive_more.workspace = true
thiserror.workspace = true
serde = { workspace = true, optional = true }

[build-dependencies]
pest_generator.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
criterion.workspace = true
iai-callgrind.workspace = true

[[bench]]
name = "vmf_parser_bench"
harness = false

[[bench]]
name = "parser_iai_bench"
harness = false

[features]
default = []
debug_assert_info = []
serialization = ["dep:serde", "indexmap/serde"]
