[package]
name = "source-vpk"
description = "Fast, safe and ergonomic support for Source Engine VPK archives."
readme = "README.md"
keywords = ["source-engine", "vpk", "archive", "gamedev"]
categories = ["game-development", "filesystem"]
repository = "https://github.com/LaVashikk/SourceRS/tree/main/crates/source-vpk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
crc32fast.workspace = true
indexmap.workspace = true
md-5.workspace = true
thiserror.workspace = true
serde = { workspace = true, optional = true }

[dev-dependencies]
tempfile.workspace = true

[features]
default = []
serde = ["dep:serde", "indexmap/serde"]
