[package]
name = "source-vmt"
description = "Rust parser and manager for Source Engine VMT files, supporting patch inheritance, material proxies, and key interning"
readme = "README.md"
keywords = ["source-engine", "sdk", "gamedev"]
categories = ["game-development"]
repository = "https://github.com/LaVashikk/SourceRS/tree/main/crates/source-vmt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
source-kv.workspace = true
serde.workspace = true
indexmap = { workspace = true, features = ["serde"] }
source-fs = { workspace = true, optional = true }
dashmap = { workspace = true, optional = true }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "vmt_bench"
harness = false

[features]
default = []
intern_keys = ["dep:dashmap"]
material_system = ["dep:source-fs"]
